default:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: 172.30.0.3
      port: 25
      enable_starttls_auto: false
      authentication: :login
      domain: example.net
      user_name: redmine@example.net
      password: password